---
title: "R386_ad_dapc"
author: "fk506cni"
date: "2020/12/10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# install.packages("pegas")

library("ape")
library("pegas")
library("seqinr")
library("ggplot2")

library("adegenet")
packageDescription("adegenet", fields = "Version")
```


```{r}
help.search("Hardy-Weinberg")
?spca
adegenetWeb()
?adegenet
```


```{r}
data("nancycats")
is.genind(nancycats)

# nancycats@tab

obj <- read.genetix(system.file("files/nancycats.gtx",package="adegenet"))
obj$call

toto <- eval(obj$call)
identical(obj, toto)

# data("nancycats")
catpop <- genind2genpop(nancycats)
catpop
```


```{r}

temp <- lapply(1:30, function(i) sample(1:9, 4, replace=TRUE))
temp <- sapply(temp, paste, collapse="")
temp <- matrix(temp, nrow=10, dimnames=list(paste("ind",1:10), paste("loc",1:3)))
temp
obj <- df2genind(temp, ploidy = 4, sep="")

dat <- read.table(system.file("files/AFLP.txt",package="adegenet"), header=TRUE)
dat

obj <- df2genind(dat, ploidy=1, type="PA")
obj

obj@tab
pop(obj) <- rep(c("a","b"),4:3)
obj2 <- genind2genpop(obj)
obj2@tab
```


```{r}
xx <- tab(obj, NA.method ="mean")
pca1 <- dudi.pca(xx, scannf = F, scale=F)
temp <- as.integer(pop(obj))
temp
myCol <- transp(c("blue", "red"), .7)[temp]
myPch <- c(15, 17)[temp]

plot(pca1$li, col=myCol, cex=3, pch=myPch)

# install.packages("wordcloud")
library(wordcloud)
textplot(pca1$li[,1], pca1$li[,2], words=rownames(xx), cex=1.4, new=FALSE)

abline(h=0,v=0,col="grey",lty=2)
s.arrow(pca1$c1*.5, add.plot=TRUE)
legend("topright", pch=c(15,17), col=transp(c("blue","red"),.7),
leg=c("Group A","Group B"), pt.cex=2)
```



```{r}
dat <- matrix(sample(c("a","t","g","c"), 15, replace=TRUE),nrow=3)
rownames(dat) <- paste("genot.", 1:3)
colnames(dat) <- 1:5
dat

obj <- df2genind(dat, ploidy=1)
tab(obj)
```


```{r}
# library(adegenet)
data(dapcIllus)
class(dapcIllus)
names(dapcIllus)
x <- dapcIllus$a
grp <- find.clusters(x, max.n.clust=40)
# grp <- find.clusters(x, max.n.clust=40, n.pca = 110, n.clust = 6)
```

```{r}
head(grp$Kstat, 8)
grp$grp
table(pop((x)), grp$grp)
```

```{r}
dapc1 <- dapc(x, grp$grp)
dapc1

scatter(dapc1)
```

