---
title: "150compare_FB"
author: "fkeita"
date: "2018/1/17"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE,cache.lazy = FALSE, echo=TRUE)
source("http://bioconductor.org/biocLite.R")
require("stringr")
require("MASS")
require("ggplot2")
require("dplyr")
require("magrittr")
require(extrafont)
loadfonts(quiet = T)

#biocLite("GEOquery")
##require(GEOquery)



set.seed("20171231")
```


```{r}
annot <- read.table(file = "./matrix4coranal_symln.tsv",header = T,sep = "\t",row.names = 1)
mas5 <- read.table(file="./mas5exprs_symln.tsv", header = T, sep = "\t",row.names = 1)
rob <- read.table(file="./rob_exprs.tsv", header = T, sep = "\t",row.names = 1)
logical_center <- read.table(file = "./logicalcenter_symln.tsv", header = T, sep = "\t",row.names = 1)
ccle_annot <- read.table(file = "./CCLE_Expression.Arrays.sif_2012-10-18.txt",header = T,sep = "\t",stringsAsFactors = F)
```


```{r}
cels_normaize <- function(celfiles, threads=4, method="mas5"){
  require(doParallel)
  require(foreach)
  #require(affy)
  
  #print(celfiles)
  start <- Sys.time()
  cl <- makeCluster(threads)
  registerDoParallel(cl)
  if(method=="mas5"){
    norm_func <- function(cel_i){
      return(affy::exprs(affy::mas5(affy::ReadAffy(filenames =cel_i))))
    }
  }else if(method=="rob"){
    norm_func <- function(cel_i){
      return(affy::exprs(RobLoxBioC::robloxbioc(affy::ReadAffy(filenames =cel_i))))
    }
  }else{
    print("method is mas5 or rob.")
  }
  
  norm4each <- foreach(i=c(1:length(celfiles)),.export = c("celfiles", "norm_func"),
                    .combine = "cbind",.packages = c("affy","RobLoxBioC"),.verbose = F) %dopar% {
                    sample_i <- norm_func(celfiles[i])
                    sample_i
                    }
  
  stopCluster(cl)
  finish <- Sys.time()
  time_foreach <- finish - start
  print(time_foreach)
  return(norm4each)
}
```

```{r}
savetsv <- function(table){
  table_name <- deparse(substitute(table))
  file_name <- paste(table_name, ".tsv",sep = "", collapse = "")
  write.table(x = table,file = file_name,sep = "\t",row.names = T, col.names = NA)
  print("file saved.")
}

readtsv <- function(file){
  table <- read.table(file = file,header = T,sep = "\t",row.names = 1,stringsAsFactors = F)
  return(table)
}

ggsave2 <- function(plot, wid=9, hei=9){
  plot_name <- deparse(substitute(plot))
  file_name <- paste(plot_name, ".tiff", sep = "",collapse = "")
  ggsave(filename = file_name,plot = plot,device = "tiff",width = wid, height = hei,dpi = 300,units = "cm")
}
```


```{r}
annot_fb <- annot[annot$category=="Fibroblasts",]
savetsv(annot_fb)
```


```{r}
ccle_cels <- list.files(path = "./ccle_cels_symln", pattern = ".CEL|.cel.gz",full.names = T)

ccle_mas5 <- cels_normaize(celfiles = ccle_cels,method = "mas5") %>%
  as.data.frame(.)
savetsv(ccle_mas5)
rm(ccle_mas5)


```

```{r}
ccle_rob <- cels_normaize(celfiles = ccle_cels, method = "rob") %>%
  as.data.frame(.)
savetsv(ccle_rob)
rm(ccle_rob)
```


```{r}
pca_cels <- list.files(path = "./celfiles_symlin", pattern = ".CEL|.cel.gz",full.names = T)
pca_mas5 <- cels_normaize(celfiles = pca_cels, method = "mas5") %>%
  as.data.frame(.)
savetsv(pca_mas5)

rm(pca_mas5)

pca_rob <- cels_normaize(celfiles = pca_cels, method = "rob") %>%
  as.data.frame(.)
savetsv(pca_rob)
rm(pca_rob)
```


##read
```{r}
ccle_mas5 <- readtsv("./ccle_mas5.tsv") %>%
  log2()
pca_mas5 <- readtsv("./pca_mas5.tsv") %>%
  log2()

colnames(ccle_mas5) <- colnames(ccle_mas5) %>% 
  str_replace(., pattern = "HG.U133_Plus_2_", "") %>%
  str_replace(., pattern=  "Human_U133_Plus_2.0_", "") %>%
  str_replace(., pattern="\\.CEL$", "")

ccle_annot$tag <- ccle_annot$ID %>%
  str_replace(., pattern = "Human_U133_Plus_2.0_", "") %>%
  str_replace(., pattern = "Human_U133_Plus_2_", "") %>%
  str_replace(., pattern=  "HG-U133_Plus_2_", "") 
sum(ccle_annot$tag %in% colnames(ccle_mas5))
ccle_annot$tag[!ccle_annot$tag %in% colnames(ccle_mas5)]
#coltmp[!colnames(ccle_mas5) %in% ccle_annot$tag]


ccle_mas5 <- ccle_mas5[, colnames(ccle_mas5) %in% ccle_annot$tag]
```



```{r}
convertvector <- function(inputvector, matrix_in_out){
  matrix_in_out <- as.data.frame(matrix_in_out)
  colnames(matrix_in_out) <- c("in", "out")
  if (sum(inputvector %in% matrix_in_out[["in"]]) != length(inputvector)) {
    return("all inputvectors must be inclued matrix in")
  }
  else if(sum(duplicated(matrix_in_out[["in"]])!=0)){
    return("input vector must be unique")
  }
  else{
      output_vector <- c(NULL)
      for (i in inputvector){
          i_output <- matrix_in_out[matrix_in_out[,1]==i,2]
          i_output <- as.character(i_output)
          output_vector <- c(output_vector, i_output)
      }
      return(output_vector)
  }
}

colnames(ccle_mas5) <- convertvector(inputvector = colnames(ccle_mas5),matrix_in_out = cbind(ccle_annot$tag, ccle_annot$CCLE.name))
```



```{r}
fb_annot <- annot[annot$category=="Fibroblasts",]

pca_tag <- colnames(pca_mas5) %>%
  str_extract(., "^GSM[0-9]*")
pca_fb <- pca_mas5[,pca_tag %in% fb_annot$id]  %>%
  apply(., 1, median)

tmp <- cbind(pca_fb, logical_center$Fibroblasts)
cor(tmp, method = "spearman")
  
Bcells <- pca_mas5[,str_detect(colnames(pca_mas5), "^B_")] %>%
  apply(.,1,median)


dat <- ccle_mas5 %>%
  cbind(pca_fb=pca_fb, clusterB=Bcells, .)

cors <- cor(dat, method = "spearman") %>%
  as.data.frame()
dim(cors)

cors_fb <- cors[sort.list(cors$pca_fb, decreasing = T),colnames(cors) %in% c("BJHTERT_SKIN","pca_fb","clusterB")]%>%
  mutate(., rowname = rownames(.)) %>%
  mutate(., origin = str_replace(rowname, "^[A-Z0-9]*_","")) %>%
  mutate(., cell_name = str_extract(rowname, "^[A-Z0-9]*_")) %>%
  mutate(., cell_name = str_replace(.$cell_name, "_", ""))

# cors_fb$cell_name <- str_extract(rownames(cors_fb), "^[A-Z0-9]*_") %>%
#   str_replace(., "_", "")

savetsv(cors_fb)
```

```{r}
Acells <- colnames(pca_mas5) %>%
  .[str_detect(., "^A_")] %>%
  str_replace(., "^A_", "") %>%
  str_replace(., "_liver.CEL","") %>%
  str_replace_all(., "\\.","") %>%
  str_replace_all(., "_","") %>%
  toupper(.)

Acells[!Acells %in% cors_fb$cell_name]

Bcells <- colnames(pca_mas5) %>%
  .[str_detect(., "^B_")] %>%
  str_replace(., "^B_", "") %>%
  str_replace(., "_liver.CEL","") %>%
  str_replace_all(., "\\.","") %>%
  str_replace_all(., "_","") %>%
  toupper(.)

Bcells[!Acells %in% cors_fb$cell_name]

```

```{r}
cors_fb <- cors_fb %>%
  mutate(category = origin) %>%
  mutate(category = ifelse(cell_name %in% Acells, "Cluster_A", category)) %>%
  mutate(category = ifelse(cell_name %in% Bcells, "Cluster_B", category)) %>%
  mutate(fb_rank = rank(-1 *pca_fb))

cors_liver <- cors_fb[cors_fb$origin =="LIVER",] %>%
  mutate(category = ifelse(category=="LIVER", "Group_C", category))


require(ggplot2)
cmp <- ggplot()+
  geom_boxplot(data = cors_liver, mapping = aes(x=category, y=fb_rank))+
  geom_jitter(data=cors_liver,mapping = aes(x=category, y=fb_rank),colour="red")+
  xlab("Category")+ylab("Cor_rank with FB_center")+
  theme_classic(base_size = 14,base_family = "Arial")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))

cmp
ggsave(filename = "./rank_of_liver_cells.tiff",plot = cmp,width = 9, height = 9,dpi = 300,units = "cm")

cmp2 <- ggplot()+
  geom_boxplot(data = cors_liver, mapping = aes(x=category, y=pca_fb))+
  geom_jitter(data=cors_liver,mapping = aes(x=category, y=pca_fb),colour="red")+
  xlab("Category")+ylab("Cor with FB_center")+
  scale_y_continuous(limits = c(0.725, 0.85))+
  theme_classic(base_size = 14,base_family = "Arial")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))

cmp2 

ggsave(filename = "./cor_with_fb.tiff",plot = cmp2,width = 9, height = 9,dpi = 300,units = "cm")

```

```{r}
cors_suspFB <- cors_fb[cors_fb$fb_rank < 102,]
table(cors_suspFB$origin)

cors_suspFB <- cors_fb[!is.na(cors_fb$cell_name),] %>%
  filter(origin!="SMALL_INTESTINE") %>%
  filter(origin!="SALIVARY_GLAND")

denst <- ggplot()+
  geom_density(data = cors_suspFB, mapping = aes(x = fb_rank,colour=origin))

denst
```

```{r}
ggdenst2 <- function(df){
  ##require fb_rank and origin data
  require(ggplot2)
  p1 <- ggplot()+geom_density(data = df, mapping = aes(x = pca_fb,colour=origin))+
  scale_x_continuous(expand = c(0,0),limits = c(0.65,0.95))+
  scale_y_continuous(expand = c(0,0))+
  theme_classic(base_size = 14,base_family = "Arial")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))
  return(p1)
}
d_all <- ggdenst2(df = cors_suspFB)
d_all
ggsave(filename = "d_all.tiff",device = "tiff",plot = d_all,width = 36, height = 9,dpi = 300,units = "cm")
```

##additional function violin and scatt
```{r}
df <- cors_fb
control_point <- cors_fb[cors_fb$rowname=="clusterB",]$pca_fb

df$origin[!duplicated(df$origin)]

df <- df %>%
  filter(!is.element(origin, c("pca_fb","clusterB"))) %>%
  filter(!is.element(origin, c("HAEMATOPOIETIC_AND_LYMPHOID_TISSUE","BONE","SOFT_TISSUE"))) %>%
  mutate(isFBlike = F) %>%
  mutate(isFBlike = ifelse(origin=="LARGE_INTESTINE" & pca_fb > 0.81, T,isFBlike)) %>%
  mutate(isFBlike = ifelse(origin=="BREAST" & pca_fb > 0.85, T,isFBlike)) %>%
  mutate(isFBlike = ifelse(origin=="SKIN" & pca_fb > 0.85, T,isFBlike)) %>%
  mutate(isFBlike = ifelse(origin=="PLEURA" & pca_fb > 0.88, T,isFBlike)) %>%
  mutate(isFBlike = ifelse(origin=="LUNG" & pca_fb > 0.85, T,isFBlike)) %>%
  mutate(FBcolor = ifelse(isFBlike, "red","blue")) %>%
  mutate(origin = str_replace_all(origin, "_", " ")) %>%
  mutate(origin = tolower(origin)) %>%
  mutate(origin = str_replace(origin, "^[a-z]", toupper))



ggVS <- function(df){
  col_line <- "#e7298a"
  col_vio <- "#66a61e"
  col_t <- "red"
  col_f <- "blue"

  p <- ggplot()+
    geom_hline(yintercept = control_point,color=col_line)+
    geom_violin(data = df,mapping = aes(x=origin, y=pca_fb), trim=F,scale = "width",colour=col_vio,fill=col_vio)+
    geom_point(data=df,mapping=aes(x=origin, y=pca_fb, colour=FBcolor),show.legend = F)+
    scale_color_manual(values= c(col_t, col_f))+
    coord_flip()+
    xlab("Originated organ")+ylab("Correlation with FB")+
    theme_classic(base_size = 14,base_family = "Arial")+
    theme(axis.text=element_text(size=12),
          axis.title=element_text(size=14,face="bold"))
  return(p)
}

vioScat <- ggVS(df)
vioScat
ggsave2(vioScat,wid = 18,hei=18)
```

```{r}

```




```{r}
table(cors_suspFB$origin)
origins <- unique(cors_suspFB$origin)
origins
carcinomas <- origins[c(2,4,8,9,10,11,12,14,16,18,19,20,21,22)]
carcinomas

dig_car <- carcinomas[c(2,9,10,11,12,14)]
dig_car

nondig_car <- carcinomas[!carcinomas %in% dig_car]
nondig_car

noncarc <- origins[!origins %in% carcinomas]
noncarc

denst_dig <- ggdenst2(df = cors_suspFB[cors_suspFB$origin %in% dig_car,])
denst_dig

ggsave(filename = "./denst_dig.tiff",device = "tiff",plot = denst_dig,width = 18, height = 9,dpi = 300,units = "cm")

denst_nondig <- ggdenst2(df = cors_suspFB[cors_suspFB$origin %in% c(nondig_car,"LIVER"),])
denst_nondig

ggsave(filename = "./denst_nondig.tiff",device = "tiff",plot = denst_nondig,width = 18, height = 9,dpi = 300,units = "cm")

cors_sar <- cors_suspFB[cors_suspFB$origin %in% noncarc,]
denst_sar <- ggdenst2(df = cors_sar)

denst_sar
ggsave(filename = "./denst_sar.tiff",device = "tiff",plot = denst_sar,width = 27, height = 9,dpi = 300,units = "cm")

require(grid)
require(gridExtra)

#g1 <- grid.arrange(denst_car, denst_sar)
```

```{r}
crk <- cors_suspFB[cors_suspFB$origin =="LARGE_INTESTINE",]
h_just <- 0
sc <- ggplot()+
  geom_violin(data=crk, mapping = aes(x=1, y=pca_fb), trim=F,colour="gray")+
  geom_point(data=crk, mapping = aes(x=1, y= pca_fb))+
  geom_text(data=crk, mapping = aes(x=1.01, y=pca_fb, label=cell_name,hjust=h_just,colour="red"),show.legend = F)+
  scale_x_continuous(limits = c(0.5,1.5))+
  xlab("Large_intestine")+
  ylab("cor_with_FB")+
  theme_classic(base_size = 14,base_family = "Arial")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank()
        )
sc

ggsave2(sc)


```

```{r}
cor_FBs <- cors_suspFB[cors_suspFB$origin %in% c("LARGE_INTESTINE", "BREAST", "SKIN","OESOPHAGUS","UPPER_AERODIGESTIVE_TRACT","LIVER","URINARY_TRACT","PLEURA","LUNG"),] %>%
  mutate(., origin_label = factor(.$origin,
                                  levels = c("LARGE_INTESTINE", "BREAST",  "SKIN", "OESOPHAGUS", 
                                             "UPPER_AERODIGESTIVE_TRACT", "LIVER", "URINARY_TRACT","PLEURA","LUNG"),
                                  labels = c("LARGE_INT", "BREAST",  "SKIN", "OESOPH", 
                                             "UA_T", "LIVER", "UR_T","PLEURA","LUNG")))

##factor(cor_FBs$origin,levels = c("LARGE_INTESTINE", "BREAST", "SKIN","OESOPHAGUS"))
h_just <- -0.1

sc <- ggplot()+
  geom_violin(data=cor_FBs, mapping = aes(x=origin_label, y=pca_fb), trim=F,colour="gray")+
  geom_point(data=cor_FBs, mapping = aes(x=origin_label, y= pca_fb))+
  geom_text(data=cor_FBs, mapping = aes(x=origin_label, y=pca_fb, label=cell_name,hjust=h_just,colour="red"),show.legend = F)+
  xlab("Origin")+
  ylab("cor_with_FB")+
  theme_classic(base_size = 14,base_family = "Arial")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"),
        axis.ticks.x = element_blank()
        )
sc
ggsave2(sc,wid = 18,hei = 18)

table(cor_FBs$origin)

cor_FBselected <- cor_FBs %>%
  mutate(cell_name=ifelse(origin=="LARGE_INTESTINE" & pca_fb < 0.81, "",cell_name)) %>%
  mutate(cell_name=ifelse(origin=="BREAST" & pca_fb < 0.85, "",cell_name)) %>%
  mutate(cell_name=ifelse(origin=="SKIN" & pca_fb < 0.85, "",cell_name)) %>%
  mutate(cell_name=ifelse(origin=="PLEURA" & pca_fb < 0.88, "",cell_name)) %>%
  mutate(cell_name=ifelse(origin=="LUNG" & pca_fb < 0.85, "",cell_name)) %>%
  mutate(cell_name=ifelse(origin %in% c("OESOPHAGUS","UPPER_AERODIGESTIVE_TRACT","URINARY_TRACT","LIVER"), "",cell_name)) %>%
  mutate(FBsusp = ifelse(cell_name=="", "NOT", "FBlike"))

cor_FBs[cor_FBs$origin=="LUNG" & cor_FBs$pca_fb > 0.85,]



sc2 <- ggplot()+
  geom_violin(data=cor_FBselected, mapping = aes(x=origin_label, y=pca_fb), trim=F,colour="gray")+
  geom_point(data=cor_FBselected, mapping = aes(x=origin_label, y= pca_fb))+
  geom_text(data=cor_FBselected, mapping = aes(x=origin_label, y=pca_fb, label=cell_name,hjust=h_just,colour="red"),show.legend = F)+
  xlab("Origin")+
  ylab("cor_with_FB")+
  theme_classic(base_size = 14,base_family = "Arial")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"),
        axis.ticks.x = element_blank()
        )
sc2
ggsave2(sc2,wid = 18,hei = 18)
```

```{r}
ref_sort <- function(sort_vector, ref_vector){
  result_vector <- c()
  for(i in c(1:length(ref_vector))){
    index_i <- which(sort_vector==ref_vector[i])
    result_vector <- c(result_vector, index_i)
  }
  return(result_vector)
}
```


##clustering
```{r}
ccle4clst <- ccle_mas5 %>%
  .[,colnames(.) %in% cor_FBselected$rowname] %>%
  .[,ref_sort(sort_vector = colnames(.),ref_vector = cor_FBselected$rowname)]

```


#for skin
```{r}
# tag <- "SKIN"
# dist_method <- "spearman"
# clst_method <- "average"
# meta_data <- cor_FBselected %>%
#   filter(origin == tag)
# data <- ccle4clst %>%
#   .[,colnames(.) %in% cormat4clst$rowname]
```


```{r}
line_size <- 0.2
main_size <- 22
legend_size <- 18
font_family <- "Arial"
legend_label <- "legend_label"
dendfunc <- function(data,meta_data,
                     dist_method="spearman",
                     clst_method="ward.D2",
                     line_size=0.2,
                     legend_label="legend_label",legend_size=16,
                     main="", main_size=18,
                     font_family="Arial",
                     #Aposi = c(0.78,0.182),
                     #Bposi = c(0.78,0.86),
                     #blacket.size = 22,
                     labes.size = 5,
                     commentlist=NULL,
                     col_palette=NULL,
                     seg= 0.1){
    #data is data.frame
    #   column is samples, row is variables.
    #meta_data is data.frame of label column + coloring annotation column(variable for fill)
    #default font is Arial. you need to load Arial if you use it.
    require(ggplot2)
    require(grid)
    require(ggdendro)
    require(gridExtra)
    require(gtable)
    require(magrittr)
  
    ##blank grid for plotting blank
    blank_grid <- grid.rect(gp=gpar(col="white"))
  
    dend <- as.dist(1 - cor(data, method = dist_method)) %>% hclust(method = clst_method) %>% as.dendrogram
    ddata <- dendro_data(dend)
    labs <- label(ddata)
    
    dend_range <- range(c(ddata$segments$y),c(ddata$segments$yend))
    ##dend_range
    axisX <- seq(dend_range[1], dend_range[2], seg)
    
    meta_data <- meta_data %>%
      select(rowname, FBsusp)
    labs_table <- merge(x = labs,y = meta_data,by.x="label", by.y ="rowname", sort = F)
    #print(range(segment(ddata)$y)[c(2,1)])
    gL <- ggplot(data=segment(ddata))+
    geom_segment(aes(x=x, y=y, xend=xend, yend=yend),size=line_size)+
    scale_y_reverse(expand=c(0,0),limits = c(max(range(segment(ddata)$y)),0),breaks=axisX)+
    scale_x_continuous(expand = c(0,0),limits = range(segment(ddata)$x)+c(-1,1))+
    coord_flip()+
    labs(y="hight")+
     theme(axis.line.y=element_blank(),
           axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        axis.text.x = element_text(hjust = 0.5),
        panel.background=element_rect(fill="white"),
        panel.grid=element_blank(),
        text = element_text(family = font_family,size=18),
        plot.margin = margin(0,0,0,0,"npc"))
    gL

    gp1 <- ggplotGrob(gL)
    #gL
    #ggsave("gL.tiff", gL,dpi=300)
    gp1
    #class(gp1)
    #gtable_show_layout(gp1)
    
    if (is.null(col_palette)){
        col_palette <- c(FBlike= "cyan",
                         NOT ="pink")
    }
    # 
    ##factorize label
    #table(labs_table$meta_tg.Site.Primary)
    #labs_table$col <- factor(labs_table$FBsusp,
    #                       levels = c("blue","gray"))
    gR <- ggplot()+
    geom_tile(data = labs_table,
              mapping = aes_string(x=colnames(labs_table)[2],
                                   y=1,
                                   fill=colnames(labs_table)[4]))+
    scale_x_continuous(expand = c(0,0),limits = range(segment(ddata)$x)+c(-1,1))+
    scale_y_continuous(expand = c(0,0))+
    scale_fill_manual(values = col_palette)+
    labs(fill=legend_label)+
    coord_flip()+
    theme(axis.line.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        axis.title.x=element_blank(),
        panel.background=element_rect(fill="white"),
        panel.grid=element_blank(),
        text = element_text(family = font_family,size=18),
        legend.key.size = unit(1,"line"),
        plot.margin = margin(0,0,0,0, "npc")
        )
gR
    gp2 <- ggplotGrob(gR)
    #gp2 <- ggplot_gtable(ggplot_build(gR))
    #gtable_show_layout(gp2)
    gp2

    grid.draw(gp2)
    gp1
    gp2
    grid.newpage()
    maxheights <- grid::unit.pmax(gp1$heights[2:10],
                                  gp2$heights[2:10])
    gp1$heights[2:10] <- as.list(maxheights)
    gp2$heights[2:10] <- as.list(maxheights)
    
    lmat <- rbind(c(1,1,1,1),
                  c(1,3,2,1),
                  c(1,1,1,1))
    lwid <- c(0.01, 2, 1.5, 0.01)
    lhei <- c(0.01,1,0.01)

    gar <- grid.arrange(blank_grid, gp2, gp1,
                        layout_matrix=lmat,heights=lhei, widths=lwid,
                        top=textGrob(main,
                        gp=gpar(fontsize=main_size,
                                fontfamily=font_family))
                        )
    grid.draw(gar)
    return(gar)
}

#d <- dendfunc(data = data, meta_data = meta_data,clst_method = clst_method,legend_label = "dist2FB",main = tag)



```

```{r}
data4clst <- ccle4clst
meta4clst <- cor_FBselected

fb_table <-  table(data.frame(meta4clst$origin, meta4clst$FBsusp))
write.table(fb_table, file = "fbtable.csv")

tg2ggsave <- function(tag, data4clst, meta4clst,clst_method = "average",wid = 9, hei =9, seg=0.1){
  meta_data <- meta4clst %>%
    filter(origin == tag)
  main <- tag %>%
    tolower() %>%
    str_replace("^[a-z]", toupper) %>%
    str_replace("_", " ")
  
  data <- data4clst %>%
    .[,colnames(.) %in% meta_data$rowname]
  d <- dendfunc(data = data, meta_data = meta_data,clst_method = clst_method,legend_label = "Type",main = main,line_size = 0.3,seg=seg)
  
  file_name <- paste(tag,"_",clst_method, ".tiff", sep = "",collapse = "")
  unit <- "cm"
  ggsave(filename = file_name,plot = d,device = "tiff",width = wid, height = hei,dpi = 300,units = "cm")
}

tg2ggsave(tag = "LARGE_INTESTINE",data4clst = data4clst, meta4clst = meta4clst)
tg2ggsave(tag = "SKIN",data4clst = data4clst, meta4clst = meta4clst)
tg2ggsave(tag = "BREAST",data4clst = data4clst, meta4clst = meta4clst)
tg2ggsave(tag = "PLEURA",data4clst = data4clst, meta4clst = meta4clst)
tg2ggsave(tag = "LUNG",data4clst = data4clst, meta4clst = meta4clst)

tg2ggsave(tag = "LARGE_INTESTINE",data4clst = data4clst, meta4clst = meta4clst, clst_method = "ward.D2")
tg2ggsave(tag = "SKIN",data4clst = data4clst, meta4clst = meta4clst, clst_method = "ward.D2")
tg2ggsave(tag = "BREAST",data4clst = data4clst, meta4clst = meta4clst, clst_method = "ward.D2")
tg2ggsave(tag = "PLEURA",data4clst = data4clst, meta4clst = meta4clst,clst_method = "ward.D2")
tg2ggsave(tag = "LUNG",data4clst = data4clst, meta4clst = meta4clst,clst_method = "ward.D2")
```



```{r}
hg_annot <-  read.csv(file = "./HG-U133_Plus_2.na36.annot.csv.gz",header = T,sep = ",",stringsAsFactors = F, skip = 25)


genes <- c("KRT19","ALB","AFP","DES" ,"VIM", "VWF","PECAM1","CD68","ACTA2") %>%
  limma::alias2SymbolTable()
genes

genes2 <- c("KRT19","ALB","VIM", "VWF","PECAM1","CD68","ACTA2","AFP","CEACAM5","MUC16","GAPDH","ACTB","B2M","HRPT1","TFRC") %>%
  limma::alias2SymbolTable()

tmp_hg_annot <- hg_annot %>%
  filter(is.element(Gene.Symbol, genes))


bil_annot <- ccle_annot %>%
  filter(Site.Primary=="biliary_tract")

bil <- ccle_mas5 %>%
  .[,colnames(.) %in% bil_annot$CCLE.name]

liv <- ccle_mas5 %>%
  .[,str_detect(colnames(.),"_LIVER")] %>%
  .[,str_replace(colnames(.),"_LIVER","") %in% Acells]

billiv <- cbind(bil, liv) %>%
  merge(x=., y=tmp_hg_annot,by.x=0, by.y=1, sort=F) %>%
  .[sort.list(.$Gene.Symbol),] %>%
  mutate(rownames=paste(Gene.Symbol, Row.names, sep = "_"))

d4h <- billiv[,c(2:19)] %>%
  `rownames<-`(.$rownames) %>%
  as.matrix()

sample_label <- colnames(d4h) %>%
  str_replace(.,pattern = "_[_A-Z]*$","")
sample_label

gene_label <- billiv$rownames

colslider <- ifelse(str_detect(colnames(d4h), "_LIVER"),"salmon","cyan")
colslider

#rownames(d4h) <- sample_lable

gplots::heatmap.2(x = d4h,Rowv = T, Colv = T,dendrogram = "both",col = gplots::bluered(256),trace = "none",cexCol = 1,labRow = gene_label,srtCol = 45, srtRow = 45,main = "gene expression LIV&BIL cell lines",symbreaks=F,symm=F,symkey=F,labCol = sample_label,ColSideColors = colslider,hclustfun = function(x) hclust(x,method = "ward.D"),distfun = function(x) as.dist(1-cor(t(x),method = "spearman")), lwid = c(3,10))

gplots::heatmap.2(x = d4h,Rowv = F, Colv = T,dendrogram = "col",col = gplots::bluered(256),trace = "none",cexCol = 1,labRow = gene_label,srtCol = 45, srtRow = 45, main = "gene expression LIV&BIL cell lines",symbreaks=F,symm=F,symkey=F,labCol = sample_label,ColSideColors = colslider,hclustfun = function(x) hclust(x,method = "ward.D"),distfun = function(x) as.dist(1-cor(t(x),method = "spearman")), lwid = c(3,10))

gplots::heatmap.2(x = d4h,Rowv = F, Colv = F,dendrogram = "none",col = gplots::bluered(256),trace = "none",cexCol = 1,labRow = gene_label,srtCol = 45, srtRow = 45, main = "gene expression LIV&BIL cell lines",symbreaks=F,symm=F,symkey=F,labCol = sample_label,ColSideColors = colslider,hclustfun = function(x) hclust(x,method = "ward.D"),distfun = function(x) as.dist(1-cor(t(x),method = "spearman")), lwid = c(3,10))

savetsv(billiv)
```



##sessioninfo
```{r}
sessionInfo()
Sys.time()
Sys.info()
```


##function for save attached pkgs from sessioninfo
```{r}
ses2ris <- function(dir="./ses_ris", ver=T){
  require("magrittr")
  require("stringr")
  
  if(!file.exists(dir)){
    dir.create(dir)
  }
  
  end_out <- function(pac, ver, dir){
    pac_ver <- packageVersion(pac)
  
    if(ver){
      out_file <- paste(pac, "_", pac_ver, ".ris",sep = "")
    }else{
      out_file <- paste(pac, ".ris",sep = "")
    }
    print(out_file)
  
    ##pac_cit <- utils:::print.bibentry(citation(pac), style = "Bibtex")
    pac_cit <- print(citation(pac),bibtex=TRUE)
  
    double_q <- "\""
    if(!is.na(pac_cit[1]$title)){
      pac_cit[1]$title <- str_replace(pac_cit[1]$title, "---", ":")
      pac_cit[1]$title <- str_replace_all(pac_cit[1]$title, "\\'", double_q)
    }

    capture.output(toBibtex(pac_cit),file = "tmp.bib")
    
    sys_code <- paste("bib2xml tmp.bib | xml2ris  > ", dir, "/", out_file, sep="")
    print(sys_code)
    system(sys_code)
  }
  
  pacs <- sessionInfo() %>%
    .$otherPkgs %>%
    names(.)
  print(pacs)
  sapply(X = pacs, FUN = end_out, ver=ver, dir=dir)
  
  file.remove("./tmp.bib")
}


#ses2ris()
```

```{r}
sessionInfo()
ses2ris()
```